name: Daily NSE 500 Data Download

on:
  schedule:
    # Runs every weekday (Mon-Fri) at 12:30 UTC = 6:00 PM IST
    - cron: '30 12 * * 1-5'  # Runs at 12:30 UTC (6:00 PM IST), Mondayâ€“Friday
  workflow_dispatch:  # allows you to manually trigger it too

jobs:
  download-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # or your version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run NSE data download script
        run: |
          python NSE500Datapull.py
